- name: simple_sequence
  rules:
    - rule: this is a test
      name: test
      export: true
  tests:
    good:
      - this:1@1,is:2@1,a:3@1,test:4@1
    bad:
      - this:1@1,is:1@1
      - this:1@1,is:2@1,a:3@1,test:4@1,too:5@1
      - a:3@1,is:2@1,test:4@1,this:1@1
      - a:3@1,a:3@1,a:3@1,a:3@1
